# Generated by Django 5.0 on 2023-12-04 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('opcao1', models.CharField(max_length=255)),
                ('opcao2', models.CharField(max_length=255)),
                ('opcao3', models.CharField(max_length=255)),
                ('opcao4', models.CharField(max_length=255)),
                ('opcao5', models.CharField(max_length=255)),
                ('opcao6', models.CharField(max_length=255)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=10)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.enquete')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
