# Generated by Django 5.0 on 2023-12-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='finalizado',
            field=models.BooleanField(default=True),
        ),
    ]
